name: Main Workflow
run-name: ${{ github.actor }} triggered "Build and Deploy" 🚀

on:
  # push:
  #   branches:
  #     - main
  #     - develop

  workflow_dispatch:
    inputs:
      environment:
        description: 'The deployment environment'
        required: true
        type: environment

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
      version: ${{ steps.extract-info.outputs.version }}
    steps:
      - name: Checkout code in the runner
        uses: actions/checkout@v4

      - name: Determine deployment environment
        id: determine-env
        run: |
          if [[ -n "${{ inputs.environment }}" ]]; then
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            echo "Unknown branch: ${{ github.ref }}"
            exit 1
          fi

      - name: Extract version, version_hash and release_date
        id: extract-info
        run: |
          version=$(awk '/versioning.version:/ {print $2}' config/version.yaml)
          version_hash=$(awk '/versioning.version_hash:/ {print $2}' config/version.yaml)
          release_date=$(awk '/versioning.release_date:/ {gsub(/'\''/, "", $2); print $2}' config/version.yaml)
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "version_hash=$version_hash" >> $GITHUB_OUTPUT
          echo "release_date=$release_date" >> $GITHUB_OUTPUT

  call-build-deploy:
    needs: prepare
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      version: ${{ needs.prepare.outputs.version }}

